// <auto-generated />
using ECommerceProductSorting.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerceProductSorting.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250418121842_finalMigration")]
    partial class finalMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECommerceProductSorting.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Apple",
                            Category = "Phones",
                            Name = "iPhone 14",
                            Price = 999m,
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Samsung",
                            Category = "Phones",
                            Name = "Galaxy S23",
                            Price = 899m,
                            Rating = 4.2999999999999998
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Apple",
                            Category = "Laptops",
                            Name = "MacBook Air",
                            Price = 1299m,
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Dell",
                            Category = "Laptops",
                            Name = "Dell XPS",
                            Price = 1099m,
                            Rating = 4.5999999999999996
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
